spring.application.name=server
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tweeterDB
spring.datasource.username=myuser
spring.datasource.password=0000

# Hibernate (EF Core equivalent) - 'update' creates tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jmx.enabled=false
# Allow React (Port 3000) to talk to Spring (Port 8080)
server.port=8080